from django.conf.urls import patterns, include, url
from wzhl_oa import settings
from main.views import *
from login.views import *
from order_form.views import *
from user_manage.views import *
from vacation.views import *
from work_out.views import *
from assets.views import *
from KPI.views import *
from personal_information.views import *
from business_trip.views import *
from contract.views import *
from seal.views import *
from repay.views import *
from used_form.views import *
from anchor_contract.views import *
from organization.views import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wzhl_oa.views.home', name='home'),
    # url(r'^wzhl_oa/', include('wzhl_oa.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login),
    url(r'^login_auth/', login_auth),
    url(r'^logout/', logout),
    url(r'^accounts/login/$',not_login),
    url(r'^main/', main),
    url(r'^chpasswd/', chpasswd),
    url(r'^post_chpasswd/', post_chpasswd),
    url(r'^order_form/', order_form),
    url(r'^order_form_data/', order_form_data),
    url(r'^order_form_dropdown/', order_form_dropdown),
    url(r'^order_form_save/', order_form_save),
    url(r'^last_order_form_save/', last_order_form_save),
    url(r'^order_form_star_save/', order_form_star_save),
    url(r'^order_form_del/', order_form_del),
    url(r'^upload_menu/', upload_menu),
    url(r'^summary/', summary),
    url(r'^used_form/', used_form),
    url(r'^vacation_table/', vacation_table),
    url(r'^vacation_table_data/', vacation_table_data),
    url(r'^vacation_table_save/', vacation_table_save),
    url(r'^vacation_table_del/', vacation_table_del),
    url(r'^vacation_refresh/', vacation_refresh_new),
    url(r'^vacation_refresh_new/', vacation_refresh_new),
    url(r'^vacation_apply/', vacation_apply),
    url(r'^vacation_apply_sub/', vacation_apply_sub),
    url(r'^vacation_apply_data/', vacation_apply_data),
    url(r'^vacation_apply_save/', vacation_apply_save),
    url(r'^vacation_apply_del/', vacation_apply_del),
    url(r'^vacation_approve_alert/', vacation_approve_alert),
    url(r'^vacation_approve/', vacation_approve),
    url(r'^vacation_approve_data/', vacation_approve_data),
    url(r'^vacation_all/', vacation_all),
    url(r'^vacation_all_data/', vacation_all_data),
    url(r'^vacation_approve_process/', vacation_approve_process),
    url(r'^vacation_log/', vacation_log),
    url(r'^vacation_log_data/', vacation_log_data),
    url(r'^vacation_export_excel/', vacation_export_excel),
    url(r'^vacation_department_list/', vacation_department_list),
    url(r'^refresh_subordinate/', refresh_subordinate),
    url(r'^work_out_apply/', work_out_apply),
    url(r'^work_out_apply_data/', work_out_apply_data),
    url(r'^work_out_apply_save/', work_out_apply_save),
    url(r'^work_out_apply_del/', work_out_apply_del),
    url(r'^work_out_approve/', work_out_approve),
    url(r'^work_out_approve_data/', work_out_approve_data),
    url(r'^work_out_all/', work_out_all),
    url(r'^work_out_all_data/', work_out_all_data),
    url(r'^work_out_approve_process/', work_out_approve_process),
    url(r'^work_out_approve_alert/', work_out_approve_alert),
    url(r'^assets_table/', assets_table),
    url(r'^assets_table2/', assets_table2),
    url(r'^assets_table3/', assets_table3),
    url(r'^assets_table4/', assets_table4),
    url(r'^assets_table_data/', assets_table_data),
    url(r'^assets_table_data2/', assets_table_data2),
    url(r'^assets_table_data3/', assets_table_data3),
    url(r'^assets_table_data4/', assets_table_data4),
    url(r'^assets_table_dropdown/', assets_table_dropdown),
    url(r'^assets_table_save/', assets_table_save),
    url(r'^assets_table_save2/', assets_table_save2),
    url(r'^assets_table_save3/', assets_table_save3),
    url(r'^assets_table_save4/', assets_table_save4),
    url(r'^assets_export_excel/', assets_export_excel),
    url(r'^assets_export_excel2/', assets_export_excel2),
    url(r'^assets_export_excel3/', assets_export_excel3),
    url(r'^assets_export_excel4/', assets_export_excel4),
    url(r'^assets_refresh/', assets_refresh),
    url(r'^assets_log/', assets_log),
    url(r'^assets_log_data/', assets_log_data),
    url(r'^KPI_table/', KPI_table),
    url(r'^KPI_table_data/', KPI_table_data),
    url(r'^KPI_table_export_all/', KPI_table_export_all),
    url(r'^KPI_set_session/', KPI_set_session),
    url(r'^KPI_table_detail/', KPI_table_detail),
    url(r'^KPI_table_detail_data/', KPI_table_detail_data),
    url(r'^KPI_table_detail_save/', KPI_table_detail_save),
    url(r'^KPI_table_detail_del/', KPI_table_detail_del),
    url(r'^KPI_table_detail_comment_save/', KPI_table_detail_comment_save),
    url(r'^KPI_table_detail_commit/', KPI_table_detail_commit),
    url(r'^KPI_approve_alert/', KPI_approve_alert),
    url(r'^KPI_table_approve/', KPI_table_approve),
    url(r'^KPI_table_approve_data/', KPI_table_approve_data),
    url(r'^KPI_table_all/', KPI_table_all),
    url(r'^KPI_table_all_data/', KPI_table_all_data),
    url(r'^KPI_table_detail_approve/', KPI_table_detail_approve),
    url(r'^KPI_table_detail_approve_commit/', KPI_table_detail_approve_commit),
    url(r'^KPI_upload_conf/',KPI_upload_conf),
    url(r'^KPI_ban_save/',KPI_ban_save),
    url(r'^KPI_table_name_list/',KPI_table_name_list),
    url(r'^create_excel/', create_excel),
    url(r'^create_excel_all/', create_excel_all),
    url(r'^personal_information_table/', personal_information_table),
    url(r'^personal_information_table_data/', personal_information_table_data),
    url(r'^personal_information_table_detail/', personal_information_table_detail),
    url(r'^personal_information_set_session/', personal_information_set_session),
    url(r'^personal_information_interview_data/', personal_information_interview_data),
    url(r'^personal_information_interview_set_session/', personal_information_interview_set_session),
    url(r'^personal_information_interview_detail/', personal_information_interview_detail),
    url(r'^business_trip_table/', business_trip_table),
    url(r'^business_trip_table_data/', business_trip_table_data),
    url(r'^business_trip_table_save/', business_trip_table_save),
    url(r'^business_trip_table_del/', business_trip_table_del),
    url(r'^business_trip_set_session/', business_trip_set_session),
    url(r'^business_trip_budget/', business_trip_budget),
    url(r'^business_trip_budget_data/', business_trip_budget_data),
    url(r'^business_trip_budget_save/', business_trip_budget_save),
    url(r'^business_trip_budget_del/', business_trip_budget_del),
    url(r'^business_trip_budget_sub_data/', business_trip_budget_sub_data),
    url(r'^business_trip_budget_sub_save/', business_trip_budget_sub_save),
    url(r'^business_trip_budget_sub_del/', business_trip_budget_sub_del),
    url(r'^business_trip_detail/', business_trip_detail),
    url(r'^business_trip_detail_data/', business_trip_detail_data),
    url(r'^business_trip_detail_save/', business_trip_detail_save),
    url(r'^business_trip_detail_del/', business_trip_detail_del),
    url(r'^business_trip_approve/', business_trip_approve),
    url(r'^business_trip_approve_data/', business_trip_approve_data),
    url(r'^business_trip_approve_process/', business_trip_approve_process),
    url(r'^business_trip_create_excel/', business_trip_create_excel),
    url(r'^business_trip_approve_alert/', business_trip_approve_alert),
    url(r'^contract_apply/', contract_apply),
    url(r'^contract_apply_data/', contract_apply_data),
    url(r'^contract_set_session/', contract_set_session),
    url(r'^contract_apply_detail/', contract_apply_detail),
    url(r'^contract_approve/', contract_approve),
    url(r'^contract_approve_data/', contract_approve_data),
    url(r'^contract_all/', contract_all),
    url(r'^contract_all_data/', contract_all_data),
    url(r'^contract_get_upload/', contract_get_upload),
    url(r'^contract_approve_process/', contract_approve_process),
    url(r'^contract_process_detail_data/', contract_process_detail_data),
    url(r'^contract_create_excel/', contract_create_excel),
    url(r'^contract_approve_alert/', contract_approve_alert),
    url(r'^export_contract_list/', export_contract_list),
    url(r'^seal_apply/', seal_apply),
    url(r'^seal_apply_data/', seal_apply_data),
    url(r'^seal_set_session/', seal_set_session),
    url(r'^seal_apply_detail/', seal_apply_detail),
    url(r'^seal_apply_detail_sub/', seal_apply_detail_sub),
    url(r'^seal_approve/', seal_approve),
    url(r'^seal_approve_data/', seal_approve_data),
    url(r'^seal_all/', seal_all),
    url(r'^seal_all_data/', seal_all_data),
    url(r'^seal_get_upload/', seal_get_upload),
    url(r'^seal_approve_process/', seal_approve_process),
    url(r'^seal_process_detail_data/', seal_process_detail_data),
    url(r'^seal_create_excel/', seal_create_excel),
    url(r'^seal_approve_alert/', seal_approve_alert),
    url(r'^export_seal_list/', export_seal_list),
    url(r'^budget_table/', budget_table),
    url(r'^budget_table_data/', budget_table_data),
    url(r'^budget_table_save/', budget_table_save),
    url(r'^budget_table_del/', budget_table_del),
    url(r'^repay_log/', repay_log),
    url(r'^repay_log_data/', repay_log_data),
    url(r'^repay_apply_bank/', repay_apply_bank),
    url(r'^repay_apply_bank_detail/', repay_apply_bank_detail),
    url(r'^repay_apply_sub/', repay_apply_sub),
    url(r'^repay_apply_data/', repay_apply_data),
    url(r'^repay_apply_save/', repay_apply_save),
    url(r'^repay_apply_del/', repay_apply_del),
    url(r'^repay_approve/', repay_approve),
    url(r'^repay_approve_data/', repay_approve_data),
    url(r'^repay_approve_process/', repay_approve_process),
    url(r'^repay_all/', repay_all),
    url(r'^repay_all_data/', repay_all_data),
    url(r'^repay_process_detail_data/', repay_process_detail_data),
    url(r'^anchor_contract_table/', anchor_contract_table),
    url(r'^anchor_contract_data/', anchor_contract_data),
    url(r'^anchor_contract_view/', anchor_contract_view),
    url(r'^anchor_contract_sign/', anchor_contract_sign),
    url(r'^organization_main/', organization_main),
    url(r'^organization_sub1/', organization_sub1),
)
